[package]
name = "yadbro/my-work-game"
version = "0.21.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = [
	"YadBro (https://github.com/YadBro)"
]
exclude = ["wally.lock", "test", "Packages", "tests"]