[package]
name = "yadbro/my-work-game"
version = "0.9.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = [
	"YadBro (https://github.com/YadBro)"
]
include = ["wally.toml", "wally.lock"]
exclude = ["**"]